apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: webapps
spec:
  type: ClusterIP
  selector:
    app: bankapp
    version: blue # This can be changed to "green" when switching traffic
